device: cpu

train_data_filename: ./data/ct_dma/ct_dma_test.pkl
valid_data_filename: ./data/ct_dma/ct_dma_valid.pkl
test_data_filename: ./data/ct_dma/ct_dma_test.pkl

# retrain: true

max_epochs: 50
batch_size: 32

max_seqlen: 144

# n_samples: 16
# init_seqlen: 18
# min_seqlen: 36


# lat_size: 250
# lon_size: 270
# sog_size: 30
# cog_size: 72
# n_lat_embd: 256
# n_lon_embd: 256
# n_sog_embd: 128
# n_cog_embd: 128
# lat_min: 55.5
# lat_max: 58.0
# lon_min: 10.3
# lon_max: 13

# mode: pos
# sample_mode: pos_vicinity
# top_k: 10
# r_vicinity: 40

# blur: true
# blur_learnable: false
# blur_loss_w: 1.0
# blur_n: 2



# n_head: 8
# n_layer: 8
# full_size: 652  # (lat_size + lon_size + sog_size + cog_size)
# n_embd: 768  # (n_lat_embd + n_lon_embd + n_sog_embd + n_cog_embd)
# embd_pdrop: 0.1
# resid_pdrop: 0.1
# attn_pdrop: 0.1

# learning_rate: 6e-4
# betas: [0.9, 0.95]
# grad_norm_clip: 1.0
# weight_decay: 0.1
# lr_decay: true
# warmup_tokens: 10240  # (512 * 20)
# final_tokens: 260e9
# num_workers: 4